# configs/train_umcu_paper1.yaml

# --- Basic Setup ---
name: qstar
suffix: paper_PD0p1_TV0p01_lq20
gpu_ids: '0'
checkpoints_dir: checkpoints/trained_model_paper_testcode
model: qmap_synth
seed: 0

# --- Data ---
dataroot: /localscratch/jlune/datasets/UMCU/UMCU_paper1_all/
data_csv_name: _umcu_paper1_parameters_tfe.csv
input_nc: 3
output_nc: 3
batchSize: 16
max_queuelength: 1024
patches_per_volume: 8
padcrop: 224
input_scan_types: T1w,T2w,FLAIR
train_subset_size: 0

# --- Generator / Network ---
which_model_netG: shared_attn_unet
feature_channels_G: 64,128,256
init_type: kaiming
norm_G: instance

# --- Training & Optimization ---
n_epochs: 50
n_warmup_epochs: 1
lr: 0.001
lr_policy: none
optimizer: adam
beta1: 0.9 # Adam beta1
do_val: false
eval_size: 0

# --- Losses ---
loss_content_I_l1: 1
loss_content_I_l2: 0
loss_content_pearson: 0
loss_vgg: 0.0
loss_PD_constraint: 0.1
loss_tv_reg: 0.01

# --- Rescaling / Input contrast dropout ---
rescaling_method: closed_form_least_squares_bounded
rescaling_factor_bounds: 0.2
modality_dropout_rate: 0.5
modality_dropout_max_missing: 1
modality_dropout_burnin: 0


# --- Logging / Eval ---
use_wandb: true
wandb_project: uv_test
calc_additional_metrics: true
train_phase: generator
save_epoch_freq: 5
save_latest_freq: 5